#!/usr/bin/env bash
# cc-code Plugin — Codex 侧生成器（唯一源 → 生成物）
# 用法: bash sync-codex.sh
#
# SSOT 纪律: 生成物 ⛔ 禁手改 —— 改规则只改 Claude 侧唯一源, 重跑本脚本落 codex 侧。
# 漂移检测由 verify-codex.sh 负责; 改了源没跑 sync → verify 必 FAIL。
# 覆盖: ① 双 manifest / marketplace / AGENTS.md 软链
#       ② skills/*/agents/openai.yaml（disable-model-invocation → allow_implicit_invocation 反转）
#       ③ assets/codex/agents/*.toml（agents/*.md → codex custom agent, init --codex 分发）
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

GREEN='\033[0;32m'; RED='\033[0;31m'; NC='\033[0m'
log()       { echo -e "${GREEN}[cc-code sync]${NC} $1"; }
check_env() { echo -e "${RED}[cc-code sync]${NC} $1"; exit 1; }

[[ -f "$PLUGIN_ROOT/.claude-plugin/plugin.json" ]] \
  || check_env "找不到唯一源 .claude-plugin/plugin.json —— 不在插件仓库根? "

# ══════════════════════════════════════════════════════════════════════════
# 生成物 1/2: JSON 双清单（plugin.json + marketplace.json）
#   确定性输出: 固定键序 + 2 空格缩进 + ensure_ascii=False, 重跑字节级一致
# ══════════════════════════════════════════════════════════════════════════
python3 - "$PLUGIN_ROOT" <<'PY'
import json, pathlib, re, sys

root = pathlib.Path(sys.argv[1])

def dump(path: pathlib.Path, obj: dict) -> None:
    path.write_text(json.dumps(obj, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

# 1) .codex-plugin/plugin.json ← .claude-plugin/plugin.json
#    映射: 字段原样保留, 增 skills 指针, 丢 keywords(codex manifest 无此概念)
claude = json.loads((root / ".claude-plugin/plugin.json").read_text(encoding="utf-8"))
plugin = {
    "name": claude["name"],
    "version": claude["version"],
    "description": claude["description"],
    "skills": "./skills/",
    "author": claude.get("author", {"name": claude["name"]}),
    "license": claude.get("license", "MIT"),
    "homepage": claude["homepage"],
    "repository": claude["repository"],
}
dump(root / ".codex-plugin/plugin.json", plugin)

# 2) .agents/plugins/marketplace.json ← .claude-plugin/marketplace.json
#    映射: 沿用顶层 name; interface.displayName = 插件名;
#    每插件 → local 源(./) + AVAILABLE/ON_INSTALL 政策(官方 codex marketplace 形状)
claude_mk = json.loads((root / ".claude-plugin/marketplace.json").read_text(encoding="utf-8"))
plugins = []
for p in claude_mk.get("plugins", []):
    plugins.append({
        "name": p["name"],
        "source": {"source": "local", "path": "./"},
        "policy": {"installation": "AVAILABLE", "authentication": "ON_INSTALL"},
        "category": p.get("category", "workflow"),
    })
marketplace = {
    "name": claude_mk["name"],
    "interface": {"displayName": plugins[0]["name"] if plugins else claude_mk["name"]},
    "plugins": plugins,
}
(root / ".agents/plugins").mkdir(parents=True, exist_ok=True)
dump(root / ".agents/plugins/marketplace.json", marketplace)

# 3) skills/*/agents/openai.yaml ← SKILL.md frontmatter
#    映射: disable-model-invocation: true → policy.allow_implicit_invocation: false
#    无该闸门的 skill(cc-code 协议体)不生成 —— codex 默认 implicit=true 即对齐 Claude 行为。
#    yaml 里不复述 description(SSOT: 描述唯一出处是 SKILL.md)。
gate_line = re.compile(r"^disable-model-invocation:\s*true\s*$", re.M)
n_yaml = 0
for skill_md in sorted((root / "skills").glob("*/SKILL.md")):
    head = skill_md.read_text(encoding="utf-8").split("---", 2)[1] if "---" in skill_md.read_text(encoding="utf-8") else ""
    if not gate_line.search(head):
        continue
    yaml_path = skill_md.parent / "agents" / "openai.yaml"
    yaml_path.parent.mkdir(exist_ok=True)
    yaml_path.write_text(
        "# AUTO-GENERATED by scripts/sync-codex.sh —— 禁手改, 唯一源是同级 SKILL.md frontmatter\n"
        "policy:\n"
        "  allow_implicit_invocation: false\n",
        encoding="utf-8",
    )
    n_yaml += 1
print(f"  openai.yaml: {n_yaml} 个闸门")

# 4) assets/codex/agents/*.toml ← agents/*.md
#    映射: frontmatter description → description; md 正文 → developer_instructions(单行 basic string,
#    JSON 转义集与 TOML 兼容, 最稳); model 档位映射; 角色沙箱 = 引擎级权限路由。
#    ⭐ codex 插件不分发 custom agents → 本目录是 init.sh --codex 的分发源, 落用户项目 .codex/agents/。
MODEL_MAP = {
    "haiku": ('"gpt-5.3-codex-spark"', None),
    "sonnet": ('"gpt-5.4-mini"', None),
    "opus": ('"gpt-5.4"', '"high"'),
}
SANDBOX_MAP = {  # 引擎级角色权限: 规划/验收只读, 执行可写
    "prd-plan": "read-only",
    "qa": "read-only",
    "dev": "workspace-write",
    "uiux": "workspace-write",
}

def toml_str(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)  # JSON 转义 ⊂ TOML basic string 转义

n_toml = 0
for agent_md in sorted((root / "agents").glob("*.md")):
    raw = agent_md.read_text(encoding="utf-8")
    parts = raw.split("---", 2)
    front, body = (parts[1], parts[2]) if len(parts) == 3 else ("", raw)

    def fm(key: str) -> str:
        m = re.search(rf'^{key}:\s*["\']?(.+?)["\']?\s*$', front, re.M)
        return m.group(1).strip() if m else ""

    name = fm("name") or agent_md.stem
    model, effort = MODEL_MAP.get(fm("model"), ('"gpt-5.4-mini"', None))
    toml = {
        "name": toml_str(name),
        "description": toml_str(fm("description") or name),
        "model": model,
        "model_reasoning_effort": effort,
        "sandbox_mode": f'"{SANDBOX_MAP.get(name, "workspace-write")}"',
        "developer_instructions": toml_str(body.strip()),
    }
    lines = []
    for k, v in toml.items():
        lines.append(f"{k} = {v}" if v is not None else f"# {k} = (继承父会话)")
    out = root / "assets/codex/agents" / f"{name}.toml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        f"# AUTO-GENERATED by scripts/sync-codex.sh —— 禁手改, 唯一源是 agents/{agent_md.name}\n"
        + "\n".join(lines) + "\n",
        encoding="utf-8",
    )
    n_toml += 1
print(f"  agents toml: {n_toml} 个角色")
PY

log "已生成: 双 manifest + marketplace + AGENTS.md 软链 + openai.yaml 闸门 + codex agents toml"

# ══════════════════════════════════════════════════════════════════════════
# 生成物 2/2: templates/AGENTS.md 软链 → CLAUDE.md
#   codex 读项目根 AGENTS.md; init.sh 拷模板时软链自动解引用为实体文件
# ══════════════════════════════════════════════════════════════════════════
(
  cd "$PLUGIN_ROOT/templates"
  if [[ "$(readlink AGENTS.md 2>/dev/null || true)" != "CLAUDE.md" ]]; then
    ln -sfn CLAUDE.md AGENTS.md
    log "已重建软链 templates/AGENTS.md → CLAUDE.md"
  fi
)

log "sync 完成 —— 生成物如有出入, 以 verify-codex.sh 实测为准"
